// <auto-generated />
using System;
using CustomerManagerWebApiByAlp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerManagerWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240724130551_SeedCustomers")]
    partial class SeedCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerManagerWebApiByAlp.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Up to 50% off on all items",
                            EndDate = new DateTime(2024, 8, 13, 16, 5, 51, 31, DateTimeKind.Local).AddTicks(5147),
                            Name = "Winter Sale",
                            StartDate = new DateTime(2024, 7, 14, 16, 5, 51, 31, DateTimeKind.Local).AddTicks(5114)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Buy one, get one free",
                            EndDate = new DateTime(2024, 9, 2, 16, 5, 51, 31, DateTimeKind.Local).AddTicks(5153),
                            Name = "Spring Sale",
                            StartDate = new DateTime(2024, 8, 3, 16, 5, 51, 31, DateTimeKind.Local).AddTicks(5152)
                        });
                });

            modelBuilder.Entity("CustomerManagerWebApiByAlp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            DateOfBirth = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            DateOfBirth = new DateTime(1990, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("CustomerManagerWebApiByAlp.Models.LoyaltyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("LoyaltyPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Benefits = "Free shipping, exclusive discounts",
                            CustomerId = 1,
                            EnrollmentDate = new DateTime(2024, 1, 24, 16, 5, 51, 31, DateTimeKind.Local).AddTicks(5192),
                            ProgramName = "Gold Member"
                        },
                        new
                        {
                            Id = 2,
                            Benefits = "Exclusive discounts",
                            CustomerId = 2,
                            EnrollmentDate = new DateTime(2024, 4, 24, 16, 5, 51, 31, DateTimeKind.Local).AddTicks(5206),
                            ProgramName = "Silver Member"
                        });
                });

            modelBuilder.Entity("CustomerManagerWebApiByAlp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            LastName = "User",
                            Password = "password123",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@example.com",
                            FirstName = "Regular",
                            LastName = "User",
                            Password = "password123",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailPermission")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            EmailAddress = "john.doe@example.com",
                            EmailPermission = true
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            EmailAddress = "jane.smith@example.com",
                            EmailPermission = false
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 2,
                            EmailAddress = "Example@example.com",
                            EmailPermission = true
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 1,
                            EmailAddress = "johnny.doe@example.com",
                            EmailPermission = true
                        });
                });

            modelBuilder.Entity("MobilePhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CallPermission")
                        .HasColumnType("bit");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SmsPermission")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("MobilePhones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CallPermission = true,
                            CustomerId = 1,
                            PhoneNumber = "123-456-7890",
                            SmsPermission = true
                        },
                        new
                        {
                            Id = 2,
                            CallPermission = false,
                            CustomerId = 2,
                            PhoneNumber = "987-654-3210",
                            SmsPermission = false
                        },
                        new
                        {
                            Id = 3,
                            CallPermission = true,
                            CustomerId = 1,
                            PhoneNumber = "555-555-5555",
                            SmsPermission = false
                        });
                });

            modelBuilder.Entity("CustomerManagerWebApiByAlp.Models.LoyaltyProgram", b =>
                {
                    b.HasOne("CustomerManagerWebApiByAlp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Email", b =>
                {
                    b.HasOne("CustomerManagerWebApiByAlp.Models.Customer", "Customer")
                        .WithMany("Emails")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MobilePhone", b =>
                {
                    b.HasOne("CustomerManagerWebApiByAlp.Models.Customer", "Customer")
                        .WithMany("MobilePhones")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerManagerWebApiByAlp.Models.Customer", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("MobilePhones");
                });
#pragma warning restore 612, 618
        }
    }
}
